_BASE_: "../Base-RCNN-FPN.yaml"
DATALOADER:
  RANDOM_DATA_SEED_PATH: ./assl_od/unbiased-teacher-main/dataseed/COCO_cdt_supervision.txt
  RANDOM_DATA_SEED: 0
  SUP_PERCENT: 1.0
  NUM_WORKERS: 4
DATASETS:
  TRAIN: ("coco_cdt_train",)
  TEST: ("coco_cdt_test",)
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
    NUM_CLASSES: 3
  WEIGHTS: ''
SEMISUPNET:
  Trainer: "baseline"
  BBOX_THRESHOLD: 0.7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  IMS_PER_BATCH: 24
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
TEST:
  EVAL_PERIOD: 100
  DETECTIONS_PER_IMAGE: 20
VERSION: 2
