_BASE_: "../Base-RCNN-FPN.yaml"
DATALOADER:
  RANDOM_DATA_SEED_PATH: ./assl_od/unbiased-teacher-main/dataseed/COCO_cdt_supervision.txt
  RANDOM_DATA_SEED: 1
  SUP_PERCENT: 10.0
  NUM_WORKERS: 4
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("coco_cdt_train",)
  TEST: ("coco_cdt_test",)
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
    NUM_CLASSES: 3
  WEIGHTS: ""
SEMISUPNET:
  Trainer: "baseline"
  BBOX_THRESHOLD: 0.7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  WARMUP_ITERS: 300
  IMS_PER_BATCH: 18
  BASE_LR: 0.005
  STEPS: (2000, 3000)
  MAX_ITER: 5000
TEST:
  EVAL_PERIOD: 60
  DETECTIONS_PER_IMAGE: 50
